<Project>

  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>

  <ItemGroup Label="Aspire">
    <PackageVersion Include="Aspire.Hosting.Testing" Version="$(VerAspire_Hosting)" />
  </ItemGroup>
  
  <ItemGroup Label="AWS">
    <PackageVersion Include="Amazon.CDK.Lib" Version="2.263.0" />
    <PackageVersion Include="AWSSDK.Extensions.NETCore.Setup" Version="4.0.100.7" />
    <PackageVersion Include="AWSSDK.S3" Version="4.0.101.6" />
  </ItemGroup>

  <ItemGroup Label="Microsoft">
    <PackageVersion Include="Microsoft.Extensions.DependencyModel" Version="10.0.10" />
    <PackageVersion Include="Microsoft.Extensions.Http.Resilience" Version="10.8.0" />
  </ItemGroup>

  <ItemGroup Label="Testing">
    <PackageVersion Include="TUnit" Version="1.48.6" />
  </ItemGroup>

</Project>
