<Project>

  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>

  <ItemGroup Label="Aspire">
    <PackageVersion Include="Aspire.Hosting.Testing" Version="$(VerAspire_Hosting)" />
  </ItemGroup>
  
  <ItemGroup Label="AWS">
    <PackageVersion Include="AWSSDK.Extensions.NETCore.Setup" Version="4.0.3.22" />
    <PackageVersion Include="AWSSDK.S3" Version="4.0.18.5" />
  </ItemGroup>

  <ItemGroup Label="Microsoft">
    <PackageVersion Include="Microsoft.Extensions.DependencyModel" Version="10.0.3" />
    <PackageVersion Include="Microsoft.Extensions.Http.Resilience" Version="10.3.0" />
  </ItemGroup>

  <ItemGroup Label="Testing">
    <PackageVersion Include="TUnit" Version="1.13.56" />
  </ItemGroup>

</Project>
