<Project>

  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>

  <ItemGroup Label="Aspire">
    <PackageVersion Include="Aspire.Hosting.Testing" Version="$(VerAspire_Hosting)" />
  </ItemGroup>
  
  <ItemGroup Label="AWS">
    <PackageVersion Include="AWSSDK.Extensions.NETCore.Setup" Version="4.0.3.9" />
    <PackageVersion Include="AWSSDK.S3" Version="4.0.9" />
  </ItemGroup>

  <ItemGroup Label="Microsoft">
    <PackageVersion Include="Microsoft.Extensions.DependencyModel" Version="9.0.10" />
    <PackageVersion Include="Microsoft.Extensions.Http.Resilience" Version="9.10.0" />
  </ItemGroup>

  <ItemGroup Label="Testing">
    <PackageVersion Include="Microsoft.Testing.Extensions.CodeCoverage" Version="18.1.0" />
    <PackageVersion Include="TUnit" Version="0.80.0" />
  </ItemGroup>

</Project>
