 <Project Sdk="Aspire.AppHost.Sdk/13.4.0">
  
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>$(NetCurrent);$(NetNext)</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>5bef0ff0-85cf-4d5a-b610-61504286a9ab</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Aspire.Hosting.PostGIS\Aspire.Hosting.PostGIS.csproj" IsAspireProjectResource="false" />
  </ItemGroup>

</Project>
